# Generated by Django 2.2.1 on 2019-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='question_id',
            new_name='question',
        ),
    ]
